# Generated by Django 5.1.2 on 2024-10-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
